import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { scanMcp } from "./scanner.js";
import type { McpFinding } from "./types.js";
import type { Severity } from "../types.js";

export type RegistryEntry = {
  name: string;
  source: string; // path to a config or tools/list JSON, relative to the manifest
  homepage?: string;
};

export type RegistryManifest = {
  about?: string;
  servers: RegistryEntry[];
};

export type Verdict = "CLEAN" | "WARN" | "BLOCKED" | "ERROR";

export type RegistryRow = {
  name: string;
  homepage?: string;
  verdict: Verdict;
  counts: Record<Severity, number>;
  topIssue: string;
};

function verdictFor(findings: McpFinding[]): Verdict {
  if (findings.some((f) => f.severity === "critical")) return "BLOCKED";
  if (findings.some((f) => f.severity === "high")) return "WARN";
  return "CLEAN";
}

export function scanRegistry(
  manifest: RegistryManifest,
  manifestPath: string,
): RegistryRow[] {
  const base = dirname(manifestPath);
  return manifest.servers.map((entry) => {
    const counts: Record<Severity, number> = { low: 0, medium: 0, high: 0, critical: 0 };
    let text: string;
    try {
      text = readFileSync(resolve(base, entry.source), "utf8");
    } catch {
      return {
        name: entry.name,
        homepage: entry.homepage,
        verdict: "ERROR" as Verdict,
        counts,
        topIssue: `could not read ${entry.source}`,
      };
    }
    const findings = scanMcp(text).findings.filter((f) => f.category !== "parse_warning");
    for (const f of findings) counts[f.severity]++;
    const worst = [...findings].sort(
      (a, b) =>
        ({ low: 1, medium: 2, high: 3, critical: 4 })[b.severity] -
        ({ low: 1, medium: 2, high: 3, critical: 4 })[a.severity],
    )[0];
    return {
      name: entry.name,
      homepage: entry.homepage,
      verdict: verdictFor(findings),
      counts,
      topIssue: worst ? `${worst.title} (${worst.severity})` : "none",
    };
  });
}

export function renderLeaderboard(rows: RegistryRow[], generatedOn: string): string {
  const order: Record<Verdict, number> = { BLOCKED: 0, WARN: 1, ERROR: 2, CLEAN: 3 };
  const sorted = [...rows].sort((a, b) => order[a.verdict] - order[b.verdict]);

  const lines: string[] = [];
  lines.push("# PromptGuard MCP Server Safety Leaderboard");
  lines.push("");
  lines.push(
    "Local, reproducible scan results for MCP servers. Generated by `scan-mcp registry`. " +
      "BLOCKED means at least one critical finding; WARN means at least one high finding; CLEAN means neither.",
  );
  lines.push("");
  lines.push(`Generated on: ${generatedOn}`);
  lines.push("");
  lines.push("| Server | Verdict | Critical | High | Medium | Top issue |");
  lines.push("|---|---|--:|--:|--:|---|");
  for (const r of sorted) {
    const name = r.homepage ? `[${r.name}](${r.homepage})` : r.name;
    lines.push(
      `| ${name} | ${r.verdict} | ${r.counts.critical} | ${r.counts.high} | ${r.counts.medium} | ${r.topIssue} |`,
    );
  }
  lines.push("");
  lines.push(
    "Methodology: each server's published tool definitions and config are scanned locally for " +
      "hardcoded secrets, tool poisoning, hidden unicode, full-schema poisoning, and tool-name shadowing. " +
      "No server code is executed. Scoring is static and conservative; a CLEAN verdict is not a security guarantee.",
  );
  return lines.join("\n") + "\n";
}

export function loadManifest(path: string): RegistryManifest {
  return JSON.parse(readFileSync(path, "utf8")) as RegistryManifest;
}
